- name: Make sure base packages are installed
  become: True
  package: name={{item}} state=installed
  with_items:
       - git
       - vim
       - tmux
       - python
       - sudo
       - python-pip
       - python-dev
       - python-virtualenv
       - python3-virtualenv
       - nginx
       - uwsgi
       - uwsgi-plugin-php
