- name: install the unbound package
  apt:
    name: unbound
- name: Create root-anchor dir
  file:
    path: /var/unbound/etc/
    state: directory

- name: Download root anchors
  get_url: 
    url: ftp://FTP.INTERNIC.NET/domain/named.cache
    dest: /var/unbound/etc/root.hints


- name: generate an unbound config
  template:
    src: unbound.j2.conf
    dest: /etc/unbound/unbound.conf
