- name: Make sure ansible is installed
  become: True
  pip:
    name: ansible, markupsafe
- name: Make sure the sudo-nopassword group exists
  become: True
  group:
    name: sudo-nopassword
    state: present
- name: Make sure the sudo-nopassword group can use sudo, without a password
  become: True
  lineinfile:
    path: /etc/sudoers
    line: "%sudo-nopassword ALL=(ALL) NOPASSWD: ALL"
- name: Create the ansible-pull user.
  become: True
  user:
    name: ansible-pull
    shell: /bin/bash
    groups: sudo-nopassword
    append: True
    system: True
- name: Add ansible-pull to crontab
  become: True
  cron:
    user: ansible-pull
    name: "ansible-pull"
    minute: "{{59 |random}}" #So that servers run updates at different times.
    job: "/usr/local/bin/ansible-pull -U {{configRepoUrl}} -d ~/ansible-pull > ~/ansible-log"
