- name: Run django migrate
  shell: /home/{{user}}/{{domain}}-venv/bin/python /home/{{user}}/{{domain}}/{{djanngo_management_command}} migrate
- name: Run django collectstatic
  shell: /home/{{user}}/{{domain}}-venv/bin/python /home/{{user}}/{{domain}}/{{djanngo_management_command}} collectstatic --noinput
